name: Devsecops Pipeline

on:
    workflow_dispatch:

jobs:
    code-quality:
        uses: .github/workflows/code-quality.yml

    secret-scan:
        uses: .github/workflows/secret-scan.yml
         
    dependency-scan:
        uses: .github/workflows/dependancy-scan.yml

    docker-scan:
        uses: .github\workflows\docker-lint.yml

