name: Hello Workflow
on:
  workflow_dispatch: 
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello Dosto"
      - name: say hello to username
        run: echo "Hello $USER"
