name: Hello Workflow
on:
  workflow_dispatch: 
    inputs:
      environment:
        description: This is the envirnment value where the workflow runs
        default: dev
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello Dosto"
      - name: say hello to username
        run: echo "Hello $USER"
