name: Docker Image scan

on:
    workflow_call:

jobs:
    image-scanner:
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker hub
              uses: docker/login-action@v3
              with:
                username: ${{vars.DOCKERHUB_USER}}
                password: ${{secrets.DOCKERHUB_TOKEN}}

            - name: Trivy Scanner
              uses: aquasecurity/trivy-action@0.33.1
              with:
                severity: 'CRITICAL'
                exit-code: '1'

