name: Portfolio
on:
    workflow_dispatch: 
    
permissions: 
    pages: write
    id-token: write
    contents: read
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            #get access to your portfolio code via pre-built actions
            - name: Checkout Code
              uses: actions/checkout@v4

            #setup github pages
            - name: Setup Github Pages
              uses: actions/configure-pages@v4
            #static code artifacts
            - name: Upload Static Files
              uses: actions/upload-pages-artifact@v4
              with:
                path: "."

            - name: Deploy to Github Pages
              id: deployment
              uses: actions/deploy-pages@v4
            
