name: Test yml code

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Code run
        run: echo "Code ran"
  build:
    runs-on: ubuntu-latest
    needs: code
    steps:
      - name: Code build
        run: echo "Code build"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Code test
        run: echo "Code tested"
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Code deploy
        run: echo "Code deployed"
